In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv('simulated_us_accidents.csv')
df

Accident_ID     City     Condition  Severity Day_of_Week  Hour  \
0               1  Houston          Rain         1      Monday    11   
1               2  Phoenix  Thunderstorm         3      Sunday    23   
2               3  Chicago           Fog         1      Friday    22   
3               4  Phoenix           Fog         1      Friday     8   
4               5  Phoenix  Thunderstorm         2     Tuesday     2   
...           ...      ...           ...       ...         ...   ...   
4995         4996  Houston          Rain         2   Wednesday     3   
4996         4997  Houston          Snow         3    Thursday    14   
4997         4998  Phoenix          Rain         4    Saturday    20   
4998         4999  Houston           Fog         3      Friday    15   
4999         5000  Phoenix          Snow         1      Friday    14   

      Injuries  Fatalities  
0            3           0  
1            1           0  
2            0           0  
3            1           0  
4            1           0  
...        ...         ...  
4995         0           0  
4996         2           0  
4997         3           0  
4998         2           0  
4999         4           0  

[5000 rows x 8 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Accident_ID  5000 non-null   int64 
 1   City         5000 non-null   object
 2   Condition    5000 non-null   object
 3   Severity     5000 non-null   int64 
 4   Day_of_Week  5000 non-null   object
 5   Hour         5000 non-null   int64 
 6   Injuries     5000 non-null   int64 
 7   Fatalities   5000 non-null   int64 
dtypes: int64(5), object(3)
memory usage: 312.6+ KB


In [4]:
df.describe()

Accident_ID     Severity        Hour     Injuries   Fatalities
count  5000.000000  5000.000000  5000.00000  5000.000000  5000.000000
mean   2500.500000     1.993000    11.44880     2.025800     0.052600
std    1443.520003     0.992748     6.87884     1.432601     0.223256
min       1.000000     1.000000     0.00000     0.000000     0.000000
25%    1250.750000     1.000000     5.00000     1.000000     0.000000
50%    2500.500000     2.000000    12.00000     2.000000     0.000000
75%    3750.250000     3.000000    17.00000     3.000000     0.000000
max    5000.000000     4.000000    23.00000    10.000000     1.000000

## 1. Limpieza de Datos

#### . Verifica si hay  valores nulos en el dataset. Decide si los eliminarás, imputarás o los manejarás de otra forma

In [5]:
df.isnull()

Accident_ID   City  Condition  Severity  Day_of_Week   Hour  Injuries  \
0           False  False      False     False        False  False     False   
1           False  False      False     False        False  False     False   
2           False  False      False     False        False  False     False   
3           False  False      False     False        False  False     False   
4           False  False      False     False        False  False     False   
...           ...    ...        ...       ...          ...    ...       ...   
4995        False  False      False     False        False  False     False   
4996        False  False      False     False        False  False     False   
4997        False  False      False     False        False  False     False   
4998        False  False      False     False        False  False     False   
4999        False  False      False     False        False  False     False   

      Fatalities  
0          False  
1          False  
2          False  
3          False  
4          False  
...          ...  
4995       False  
4996       False  
4997       False  
4998       False  
4999       False  

[5000 rows x 8 columns]

In [6]:
df.isnull().sum()

Accident_ID    0
City           0
Condition      0
Severity       0
Day_of_Week    0
Hour           0
Injuries       0
Fatalities     0
dtype: int64

##### . Revisa si hay datos duplicados y elimínalos si es necesario.


In [7]:
df_duplicado=df.drop_duplicates(subset='Accident_ID')
df_duplicado

Accident_ID     City     Condition  Severity Day_of_Week  Hour  \
0               1  Houston          Rain         1      Monday    11   
1               2  Phoenix  Thunderstorm         3      Sunday    23   
2               3  Chicago           Fog         1      Friday    22   
3               4  Phoenix           Fog         1      Friday     8   
4               5  Phoenix  Thunderstorm         2     Tuesday     2   
...           ...      ...           ...       ...         ...   ...   
4995         4996  Houston          Rain         2   Wednesday     3   
4996         4997  Houston          Snow         3    Thursday    14   
4997         4998  Phoenix          Rain         4    Saturday    20   
4998         4999  Houston           Fog         3      Friday    15   
4999         5000  Phoenix          Snow         1      Friday    14   

      Injuries  Fatalities  
0            3           0  
1            1           0  
2            0           0  
3            1           0  
4            1           0  
...        ...         ...  
4995         0           0  
4996         2           0  
4997         3           0  
4998         2           0  
4999         4           0  

[5000 rows x 8 columns]

##### . Convierte las columnas a los tipos de datos apropiados (por ejemplo, fechas, categorías, números).

In [8]:

df['Condition']=df['Condition'].astype(str)
type(df['Condition'])
df['Condition'].apply(type).unique()


array([<class 'str'>], dtype=object)

In [9]:
# Vamos agrupar valores y ordenarlos

city_severity=df.groupby(['City'])['Severity'].sum()
city_severity.sort_values(ascending=False)
city_severity

max_city_severity=city_severity.max()
max_city_severity


2044

In [10]:
df['Average Fatalities']=df['Fatalities'].sum().mean()
df


Accident_ID     City     Condition  Severity Day_of_Week  Hour  \
0               1  Houston          Rain         1      Monday    11   
1               2  Phoenix  Thunderstorm         3      Sunday    23   
2               3  Chicago           Fog         1      Friday    22   
3               4  Phoenix           Fog         1      Friday     8   
4               5  Phoenix  Thunderstorm         2     Tuesday     2   
...           ...      ...           ...       ...         ...   ...   
4995         4996  Houston          Rain         2   Wednesday     3   
4996         4997  Houston          Snow         3    Thursday    14   
4997         4998  Phoenix          Rain         4    Saturday    20   
4998         4999  Houston           Fog         3      Friday    15   
4999         5000  Phoenix          Snow         1      Friday    14   

      Injuries  Fatalities  Average Fatalities  
0            3           0               263.0  
1            1           0               263.0  
2            0           0               263.0  
3            1           0               263.0  
4            1           0               263.0  
...        ...         ...                 ...  
4995         0           0               263.0  
4996         2           0               263.0  
4997         3           0               263.0  
4998         2           0               263.0  
4999         4           0               263.0  

[5000 rows x 9 columns]

### 2. Análisis Exploratorio de Datos (EDA)


##### . Calcula estadísticas descriptivas para todas las columnas numéricas (media, mediana, desviación estándar, etc.).

In [11]:
mediana_gravedad=df['Severity'].median()
print(f"La mediana de la gravedad: {mediana_gravedad}")

La mediana de la gravedad: 2.0


In [12]:
promedio_de_std=df['Accident_ID'].std()
print(f'La desviación estándar es de: {promedio_de_std}')

La desviación estándar es de: 1443.5200033252052


##### . Identifica cuáles son las ciudades con más accidentes.


In [13]:
severity_injuries=df.groupby('City')['Injuries'].max()
df_ordenado=severity_injuries.sort_values(ascending=False).head(10)
df_ordenado


City
New York       10
Houston         9
Phoenix         9
Chicago         8
Los Angeles     7
Name: Injuries, dtype: int64

##### . Averigua en qué días de la semana ocurren más accidentes y en qué horas del día son más frecuentes.

In [90]:
day_of_week_and_hour=df.groupby(['Day_of_Week','Hour'])['Severity'].sum()
day_of_week_and_hour

Day_of_Week  Hour
Friday       0       37
             1       51
             2       54
             3       70
             4       53
                     ..
Wednesday    19      61
             20      43
             21      73
             22      49
             23      61
Name: Severity, Length: 168, dtype: int64

##### Analiza la distribución de la severidad de los accidentes. ¿Cuál es la más común y cuál la menos frecuente?

In [68]:
max_condition_severity=df.groupby('Condition')['Severity'].std()

max_condition_severity

Condition
Clear           0.991927
Fog             1.000499
Rain            0.989901
Snow            1.005195
Thunderstorm    0.977175
Name: Severity, dtype: float64

In [69]:
max_condition_severity=df.groupby('Condition')['Severity'].std().max()

max_condition_severity

1.0051953804448015

In [70]:
min_condition_severity=df.groupby('Condition')['Severity'].std().min()

min_condition_severity

0.9771749762184857

#### Determina las condiciones climáticas más asociadas a accidentes graves.


In [81]:
df['Serious Accidents']=df['Severity'] + df['Injuries']

conditions_serious_accidents=df.groupby(['City','Condition'])['Serious Accidents'].agg(['sum','mean','max'])
conditions_serious_accidents.sort_values(by='Condition',ascending=False).head(3)




sum      mean  max
City     Condition                       
Phoenix  Thunderstorm  819  3.956522   11
Chicago  Thunderstorm  828  4.181818   10
New York Thunderstorm  816  3.923077   10

### 3. Análisis de Correlaciones


##### Calcula la correlación entre la severidad, el número de lesiones y las fatalidades.


In [19]:
correlation_matrix=df[['Severity','Injuries','Fatalities']].corr()
correlation_matrix

Severity  Injuries  Fatalities
Severity    1.000000  0.010817   -0.011877
Injuries    0.010817  1.000000    0.016396
Fatalities -0.011877  0.016396    1.000000

In [20]:
hour_severity=df.groupby('Hour')['Severity'].mean()
hour_severity

Hour
0     1.965686
1     2.009390
2     1.995215
3     2.117647
4     1.949749
5     1.944186
6     1.945701
7     1.969231
8     1.966480
9     1.995455
10    1.941748
11    2.060185
12    1.963801
13    2.034483
14    2.085000
15    2.009132
16    1.968182
17    1.986667
18    2.009901
19    1.922727
20    1.958333
21    2.053812
22    1.973822
23    1.994624
Name: Severity, dtype: float64

In [21]:
# A las 3 de la mañana se producen los accidentes más graves
hour_severity.max()


2.1176470588235294

#### Analiza si hay relación entre la hora del día y la severidad de los accidentes.


In [22]:
import numpy as np
correlation=np.corrcoef(df['Hour'],df['Severity'])
correlation


array([[1.0000000e+00, 7.9325239e-05],
       [7.9325239e-05, 1.0000000e+00]])

In [23]:
condition_injuries=df.groupby('Condition')['Injuries'].mean()
condition_injuries

Condition
Clear           1.974708
Fog             2.092133
Rain            2.007612
Snow            1.980208
Thunderstorm    2.077387
Name: Injuries, dtype: float64

In [24]:
condition_injuries=df.groupby('Condition')['Injuries'].max()
condition_injuries

Condition
Clear            9
Fog             10
Rain             8
Snow             7
Thunderstorm     7
Name: Injuries, dtype: int64

In [25]:
condition_injuries=df.groupby('Condition')['Injuries'].std()
condition_injuries

Condition
Clear           1.386168
Fog             1.532650
Rain            1.402019
Snow            1.380870
Thunderstorm    1.458701
Name: Injuries, dtype: float64

### 4. Agrupaciones y Resúmenes


#### El promedio de severidad de los accidentes por ciudad.


In [26]:
city_severity_std=df.groupby('City')['Severity'].std()
city_severity_std

City
Chicago        1.006222
Houston        0.999951
Los Angeles    0.985744
New York       0.995356
Phoenix        0.976750
Name: Severity, dtype: float64

In [27]:
df['Average Injuries']=df['Injuries'].mean()

In [28]:
df['Average Fatalities']=df['Fatalities'].mean()
df

Accident_ID     City     Condition  Severity Day_of_Week  Hour  \
0               1  Houston          Rain         1      Monday    11   
1               2  Phoenix  Thunderstorm         3      Sunday    23   
2               3  Chicago           Fog         1      Friday    22   
3               4  Phoenix           Fog         1      Friday     8   
4               5  Phoenix  Thunderstorm         2     Tuesday     2   
...           ...      ...           ...       ...         ...   ...   
4995         4996  Houston          Rain         2   Wednesday     3   
4996         4997  Houston          Snow         3    Thursday    14   
4997         4998  Phoenix          Rain         4    Saturday    20   
4998         4999  Houston           Fog         3      Friday    15   
4999         5000  Phoenix          Snow         1      Friday    14   

      Injuries  Fatalities  Average Fatalities  Serious Accidents  \
0            3           0              0.0526                  4   
1            1           0              0.0526                  4   
2            0           0              0.0526                  1   
3            1           0              0.0526                  2   
4            1           0              0.0526                  3   
...        ...         ...                 ...                ...   
4995         0           0              0.0526                  2   
4996         2           0              0.0526                  5   
4997         3           0              0.0526                  7   
4998         2           0              0.0526                  5   
4999         4           0              0.0526                  5   

      Average Injuries  
0               2.0258  
1               2.0258  
2               2.0258  
3               2.0258  
4               2.0258  
...                ...  
4995            2.0258  
4996            2.0258  
4997            2.0258  
4998            2.0258  
4999            2.0258  

[5000 rows x 11 columns]

#### El total de lesiones y fatalidades en cada ciudad.


In [29]:
injuries_fatalities=df.groupby(['City','Injuries'])['Fatalities'].sum().reset_index()
injuries_fatalities.sort_values(by='City',ascending=False).head(10)


City  Injuries  Fatalities
44   Phoenix         9           0
43   Phoenix         7           1
42   Phoenix         6           2
41   Phoenix         5           0
40   Phoenix         4           6
39   Phoenix         3          13
38   Phoenix         2          21
37   Phoenix         1          14
36   Phoenix         0           6
31  New York         4           4

#### La cantidad promedio de accidentes por día

In [30]:
average_day_of_week_severity=df.groupby('Day_of_Week')['Severity'].mean()
average_day_of_week_severity

Day_of_Week
Friday       1.982379
Monday       1.962162
Saturday     2.000000
Sunday       2.018843
Thursday     1.965672
Tuesday      1.955466
Wednesday    2.067239
Name: Severity, dtype: float64

#### Las horas más críticas para cada día de la semana.



In [31]:
hour_severity_day_of_week=df.groupby(['Day_of_Week','Hour'])['Severity'].sum().reset_index()
hour_severity_day_of_week.sort_values(by=['Severity','Hour'],ascending=False)


Day_of_Week  Hour  Severity
87       Sunday    15        95
83       Sunday    11        87
27       Monday     3        87
81       Sunday     9        80
45       Monday    21        77
..          ...   ...       ...
114    Thursday    18        37
110    Thursday    14        37
58     Saturday    10        37
0        Friday     0        37
23       Friday    23        36

[168 rows x 3 columns]

In [32]:
severity=df['Severity'].mean()
severity

1.993

#### Genera un resumen de accidentes por tipo de condición climática.


In [33]:
sumarry=df.groupby('Condition')['Severity'].mean()
df['Accidents sumarry']=df['Condition'].map(sumarry)
df


Accident_ID     City     Condition  Severity Day_of_Week  Hour  \
0               1  Houston          Rain         1      Monday    11   
1               2  Phoenix  Thunderstorm         3      Sunday    23   
2               3  Chicago           Fog         1      Friday    22   
3               4  Phoenix           Fog         1      Friday     8   
4               5  Phoenix  Thunderstorm         2     Tuesday     2   
...           ...      ...           ...       ...         ...   ...   
4995         4996  Houston          Rain         2   Wednesday     3   
4996         4997  Houston          Snow         3    Thursday    14   
4997         4998  Phoenix          Rain         4    Saturday    20   
4998         4999  Houston           Fog         3      Friday    15   
4999         5000  Phoenix          Snow         1      Friday    14   

      Injuries  Fatalities  Average Fatalities  Serious Accidents  \
0            3           0              0.0526                  4   
1            1           0              0.0526                  4   
2            0           0              0.0526                  1   
3            1           0              0.0526                  2   
4            1           0              0.0526                  3   
...        ...         ...                 ...                ...   
4995         0           0              0.0526                  2   
4996         2           0              0.0526                  5   
4997         3           0              0.0526                  7   
4998         2           0              0.0526                  5   
4999         4           0              0.0526                  5   

      Average Injuries  Accidents sumarry  
0               2.0258           2.032350  
1               2.0258           1.956784  
2               2.0258           1.993789  
3               2.0258           1.993789  
4               2.0258           1.956784  
...                ...                ...  
4995            2.0258           2.032350  
4996            2.0258           2.003125  
4997            2.0258           2.032350  
4998            2.0258           1.993789  
4999            2.0258           2.003125  

[5000 rows x 12 columns]

### 6. Trabajo Avanzado con NumPy


#### Genera arrays para realizar cálculos complejos, como:


In [34]:
severity=df['Severity'].to_numpy()
day_of_week=df['Day_of_Week'].to_numpy()
hour=df['Hour'].to_numpy()
injuries=df['Injuries'].to_numpy()
fatalities=df['Fatalities'].to_numpy()
condition=df['Condition'].to_numpy()
print(severity)
print(day_of_week)
print(hour)
print(injuries)
print(fatalities)
print(condition)


[1 3 1 ... 4 3 1]
['Monday' 'Sunday' 'Friday' ... 'Saturday' 'Friday' 'Friday']
[11 23 22 ... 20 15 14]
[3 1 0 ... 3 2 4]
[0 0 0 ... 0 0 0]
['Rain' 'Thunderstorm' 'Fog' ... 'Rain' 'Fog' 'Snow']


In [35]:
severity.mean()

1.993

#### La probabilidad de que un accidente sea grave en diferentes condiciones climáticas.


##### Calcula cuántos accidentes graves hay para cada condición climática.


In [36]:

df['Max_Severity']=df['Severity']>=4
sum_condition_severity=df.groupby('Condition')['Max_Severity'].sum()
print(sum_condition_severity)
sum_condition_severity.to_numpy()

Condition
Clear            98
Fog              95
Rain            102
Snow             99
Thunderstorm     88
Name: Max_Severity, dtype: int64


array([ 98,  95, 102,  99,  88], dtype=int64)

##### Calcula el total de accidentes para cada condición climática.


In [37]:
count_max_condition_severity=df.groupby('Condition')['Severity'].count()
print(count_max_condition_severity)
count_max_condition_severity.to_numpy()

Condition
Clear           1028
Fog              966
Rain            1051
Snow             960
Thunderstorm     995
Name: Severity, dtype: int64


array([1028,  966, 1051,  960,  995], dtype=int64)

In [38]:
# Dividir accidentes graves entre el total: Para cada condición, divide le número de accidentes graves entre el total de accidentes para esa condición, Eso te dará la probalidad
# (Accidentes graves por condición) / (Total de accidentes por condición
probalidad=sum_condition_severity/count_max_condition_severity
print(probalidad)
probalidad.to_numpy()

Condition
Clear           0.095331
Fog             0.098344
Rain            0.097050
Snow            0.103125
Thunderstorm    0.088442
dtype: float64


array([0.09533074, 0.09834369, 0.09705043, 0.103125  , 0.08844221])

#### El promedio ponderado de lesiones considerando la severidad de los accidentes.


In [98]:
injuries_severity=df.groupby('Injuries')['Severity'].std()
injuries_severity

Injuries
0     0.971264
1     0.999614
2     0.994036
3     0.998934
4     1.007532
5     0.928593
6     1.037508
7     0.924870
8     0.577350
9     1.414214
10         NaN
Name: Severity, dtype: float64

#### Crea funciones personalizadas con NumPy para analizar los patrones de datos (por ejemplo, una función que calcule la proporción de accidentes fatales por ciudad).


In [65]:
def calculate_of_accidents():
    city_fatalities=df.groupby('City')['Fatalities'].sum()
    city_severity_count=df.groupby('City')['Severity'].count()
    proporcion=city_fatalities/city_severity_count
    print(proporcion)
    
calculate_of_accidents()

City
Chicago        0.046796
Houston        0.056492
Los Angeles    0.050777
New York       0.047105
Phoenix        0.061523
dtype: float64


In [82]:
df_ordenado

City
New York       10
Houston         9
Phoenix         9
Chicago         8
Los Angeles     7
Name: Injuries, dtype: int64